const Trigger = require("@akashic/trigger").Trigger;
const ServerConfigMock = require("./SeverConfigMock");
exports.onPlayCreate = new Trigger();
exports.onPlayStatusChange = new Trigger();
exports.onPlayerJoin = new Trigger();
exports.onPlayerLeave = new Trigger();
exports.onRunnerCreate = new Trigger();
exports.onRunnerRemove = new Trigger();
exports.onClientInstanceAppear = new Trigger();
exports.onClientInstanceDisappear = new Trigger();
const socket = ServerConfigMock.socket;
socket.on("playCreate", function (arg) { exports.onPlayCreate.fire(arg); });
socket.on("playStatusChange", function (arg) { exports.onPlayStatusChange.fire(arg); });
socket.on("playerJoin", function (arg) { exports.onPlayerJoin.fire(arg); });
socket.on("playerLeave", function (arg) { exports.onPlayerLeave.fire(arg); });
socket.on("runnerCreate", function (arg) { exports.onRunnerCreate.fire(arg); });
socket.on("runnerRemove", function (arg) { exports.onRunnerRemove.fire(arg); });
socket.on("clientInstanceAppear", function (arg) { exports.onClientInstanceAppear.fire(arg); });
socket.on("clientInstanceDisappear", function (arg) { exports.onClientInstanceDisappear.fire(arg); });