name: test

on:
  pull_request:
    types: [opened, synchronize]
  push:

concurrency:
  group: ${{ startsWith(github.head_ref, 'renovate/') && 'renovate' || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: ${{ !startsWith(github.head_ref, 'renovate/') }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-2022] # windows-latest 環境では e2e テストが失敗するため、暫定的対応として windows-2022 を指定
        node: [24.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm run setup
          npm run build
          npm test
        env:
          NX_DISABLE_DB: true
